function t142_checkSize(recid){var el=$("#rec"+recid).find(".t142__submit");if(el.length){var btnheight=el.height()+5;var textheight=el[0].scrollHeight;if(btnheight<textheight){var btntext=el.text();el.addClass("t142__submit-overflowed");el.html("<span class=\"t142__text\">"+btntext+"</span>")}}}
function t229_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t229__list_item a[href='"+url+"']").addClass("t-active");$(".t229__list_item a[href='"+url+"/']").addClass("t-active");$(".t229__list_item a[href='"+pathname+"']").addClass("t-active");$(".t229__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t229__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t229__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t229_setPath(pageid){}
function t229_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t229").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t229").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t229_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t229").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t229_changeBgOpacityMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t229").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll)}else{el.css("background-color",bgcolor)}})}}
function t260_init(){$(".t260").each(function(){var el=$(this);if(el.attr('data-block-init')=='yes'){}else{el.attr('data-block-init','yes');var toggler=el.find(".t260__header");var content=el.find(".t260__content");toggler.click(function(){$(this).toggleClass("t260__opened");if($(this).hasClass("t260__opened")==!0){content.slideDown()}else{content.slideUp()}})}})}
function t418_checkSize(recid){var el=$("#rec"+recid);var sizer=el.find('.t418__height');var height=sizer.height();var width=sizer.width();var ratio=width/height;var gallerywrapper=el.find(".t418__checksize");var gallerywidth=gallerywrapper.width();gallerywrapper.css({'height':((gallerywidth/ratio)+'px')});var maxwidth=el.find(".t418__height").width();var windowwidth=$(window).width();var value=windowwidth-80;if(maxwidth>windowwidth){el.find(".t418__item").css("max-width",value+"px");el.find(".t418__img").css("left","20px");el.find(".t418__img").css("right","20px")}else{el.find(".t418__item").css("max-width","");el.find(".t418__img").css("left","");el.find(".t418__img").css("right","")}}
function t418_init(recid){var el=$('#rec'+recid);var pos=0;var t418_doResize;var totalSlides=el.find('.t418__item').length;var sliderWidth=el.find('.t418__item').width();$(window).resize(function(){if(t418_doResize)clearTimeout(t418_doResize);t418_doResize=setTimeout(function(){sliderWidth=el.find('.t418__slider').width();el.find('.t418__slidecontainer').width(sliderWidth*totalSlides);console.log(sliderWidth)},200)});el.find('.t418__slidecontainer').width(sliderWidth*totalSlides);el.find('.t418__next').click(function(){slideRight(recid)});el.find('.t418__previous').click(function(){slideLeft(recid)});function slideLeft(recid){var el=$('#rec'+recid);pos--;if(pos==-1){pos=totalSlides-1}
el.find('.t418__slidecontainer').css({transform:'translate(-'+(sliderWidth*pos)+'px, 0)'})
el.find('.t418__slidecontainer').css("transition-duration",".3s");if(window.lazy=='y'){t_lazyload_update()}}
function slideRight(recid){var el=$('#rec'+recid);pos++;if(pos==totalSlides){pos=0}
el.find('.t418__slidecontainer').css({transform:'translate(-'+(sliderWidth*pos)+'px, 0)'})
el.find('.t418__slidecontainer').css("transition-duration",".3s");if(window.lazy=='y'){t_lazyload_update()}}
var swipeOptions={triggerOnTouchEnd:!0,swipeStatus:swipeStatus,allowPageScroll:"vertical",threshold:75};el.find(".t418__slidecontainer").swipe(swipeOptions);el.find(".t418__slidecontainer").swipe({tap:function(event,target){slideRight(recid)}});function swipeStatus(event,phase,direction,distance){if(phase=="move"&&(direction=="left"||direction=="right")){var duration=0;if(direction=="left"){scrollImages((sliderWidth*pos)+distance,duration)}else if(direction=="right"){scrollImages((sliderWidth*pos)-distance,duration)}}else if(phase=="cancel"){scrollImages(sliderWidth*pos)}else if(phase=="end"){if(direction=="right"){slideLeft(recid)}else if(direction=="left"){slideRight(recid)}}}
function scrollImages(distance,duration){el.find(".t418__slidecontainer").css("transition-duration",(duration/1000).toFixed(1)+"s");var value=(distance<0?"":"-")+Math.abs(distance).toString();el.find(".t418__slidecontainer").css("transform","translate("+value+"px, 0)")}}